# Generated by Django 2.2.5 on 2019-09-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='autor',
        ),
    ]
