# Generated by Django 2.2.5 on 2019-09-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0002_remove_album_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.DurationField(null=True),
        ),
    ]
